spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  profiles:
    include: oauth
    active: dev

jwt:
  secret: ${JWT_SECRET}

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

logging.level:
  org.hibernate.SQL: debug
