# 1 워크플로의 이름 지정
name: build-test

# 2 워크플로가 시작될 조건 지정
on:
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-22.04 # 3 실행 환경 지정
    #4 실행스텝지정
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Generate Envirvonment Variables File for Production
        run: |
          echo "$ENV" >> .env
          echo "$FIREBASE_PRIVATE_KEY" >> ./src/main/resources/firebase-private-key.json

        env:
          ENV: ${{ secrets.ENV }}
          FIREBASE_PRIVATE_KEY : ${{ secrets.FIREBASE_PRIVATE_KEY }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name : Test
        run: ./gradlew test

      - name: Discord Test Alarm when fail
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_BE_WEB_HOOK_URL }}
          status: ${{ job.status }}
          title: "test"
          description: "test fail"
          color: 0xff0000
          username: Github Actions

      - name: Discord Test Alarm when success
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_BE_WEB_HOOK_URL }}
          status: ${{ job.status }}
          title: "test"
          description: "test success"
          color: 0x00ff00
          username: Github Actions
